require 'rake'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |s|
    s.name        = %q{suse_gallery_wrapper}
    s.summary     = %q{SUSE Gallery wrapper.}
    s.description = %q{Nothing yet}

    s.files        = FileList['[A-Z]*', 'lib/**/*.rb']
    s.require_path = 'lib'
    #s.test_files   = Dir[*['test/**/*_test.rb']]

    s.has_rdoc         = false

    s.author = 'Cristian Mircea Messel'
    s.email = 'suse_gallery_widget@yahoo.com'

    s.homepage = "https://github.com/mess110/suse_gallery_widget"

    s.add_dependency "nokogiri"

    s.platform = Gem::Platform::RUBY
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler not available. Install it with: gem install jeweler"
end
